---
# task/configure file for hashicorp_consul
- name: "Configure for host installation"
  when: hashi_consul_deploy_method == 'host'
  block:
    - name: "Ensure default consul.hcl is removed"
      ansible.builtin.file:
        path: /etc/consul.d/consul.hcl
        state: absent

    - name: "Create consul.env"
      ansible.builtin.template:
        src: consul.env.j2
        dest: "{{ hashi_consul_config_dir }}/consul.env"
        owner: "{{ hashi_consul_user }}"
        group: "{{ hashi_consul_group }}"
        mode: "0600"

- name: "Copy consul.json template"
  ansible.builtin.template:
    src: consul.json.j2
    dest: "{{ hashi_consul_config_dir }}/consul.json"
    owner: "{{ hashi_consul_user }}"
    group: "{{ hashi_consul_group }}"
    mode: "0600"
  notify:
    - "systemctl-enable-consul"
    - "systemctl-restart-consul"

- name: "Copy extra configuration files"
  when: hashi_consul_extra_files
  block:
    - name: "Update container volume list"
      ansible.builtin.set_fact:
        hashi_consul_container_volume_map: "{{
          (hashi_consul_container_volume_map + [
          item.dest + ':' + item.dest
          ]) | unique }}"
      loop: "{{ hashi_consul_extra_files_list }}"
      loop_control:
        loop_var: item
      delegate_to: localhost

    - name: "Get extra file types"
      ansible.builtin.stat:
        path: "{{ item.src }}"
      loop: "{{ hashi_consul_extra_files_list }}"
      register: hashi_consul_extra_file_stat
      delegate_to: localhost

    - name: "Set list for file sources"
      vars:
        _hashi_consul_file_sources: []
      ansible.builtin.set_fact:
        _hashi_consul_file_sources: "{{ _hashi_consul_file_sources + [item.item] }}"
      when: item.stat.isreg
      loop: "{{ hashi_consul_extra_file_stat.results }}"
      loop_control:
        loop_var: item
      delegate_to: localhost

    - name: "Set list for directory sources"
      vars:
        _hashi_consul_dir_sources: []
      ansible.builtin.set_fact:
        _hashi_consul_dir_sources: "{{ _hashi_consul_dir_sources + [item.item] }}"
      when: item.stat.isdir
      loop: "{{ hashi_consul_extra_file_stat.results }}"
      loop_control:
        loop_var: item
      delegate_to: localhost

    - name: "Template extra file sources"
      ansible.builtin.template:
        src: "{{ item.src }}"
        dest: "{{ item.dest | regex_replace('\\.j2$', '') }}"
        owner: "{{ hashi_consul_user }}"
        group: "{{ hashi_consul_group }}"
        mode: "0700"
      loop: "{{ _hashi_consul_file_sources }}"

    - name: "Template extra directory sources"
      ansible.builtin.include_tasks: recursive_copy_extra_dirs.yml
      loop: "{{ _hashi_consul_dir_sources }}"
      loop_control:
        loop_var: dir_source_item
