---
# task/configure file for hashicorp_consul
- name: "Ensure default consul.hcl is removed"
  ansible.builtin.file:
    path: /etc/consul.d/consul.hcl
    state: absent

- name: "Copy consul.json template"
  ansible.builtin.template:
    src: consul.json.j2
    dest: "{{ hashi_consul_config_dir }}/consul.json"
    owner: "{{ hashi_consul_user }}"
    group: "{{ hashi_consul_group }}"
    mode: '0600'
  notify:
    - "systemctl-enable-consul"
    - "systemctl-restart-consul"

- name: "Create consul.env"
  ansible.builtin.template:
    src: consul.env.j2
    dest: "{{ hashi_consul_config_dir }}/consul.env"
    owner: "{{ hashi_consul_user }}"
    group: "{{ hashi_consul_group }}"
    mode: '0600'

- name: "Copy extra configuration files"
  when: hashi_consul_extra_files
  block:
    - name: "Create directory {{ hashi_consul_extra_files_dst }}"
      ansible.builtin.file:
        path: "{{ hashi_consul_extra_files_dst }}"
        state: directory
        owner: "{{ hashi_consul_user }}"
        group: "{{ hashi_consul_group }}"
        mode: '0755'

    - name: "Copy extra configuration files"
      ansible.builtin.template:
        src: "{{ item }}"
        dest: "{{ hashi_consul_extra_files_dst }}/{{ (item | basename).split('.')[:-1] | join('.')}}"
        owner: "{{ hashi_consul_user }}"
        group: "{{ hashi_consul_group }}"
        mode: '0600'
      with_fileglob:
        - "{{ hashi_consul_extra_files_src }}/*"
