---
# task/install file for hashicorp_consul
- name: "Configure hashicorp repository"
  ansible.builtin.include_role:
    name: ednz_cloud.manage_repositories
  vars:
    manage_repositories_enable_default_repo: false
    manage_repositories_enable_custom_repo: true
    manage_repositories_custom_repo: "{{ hashi_consul_repository }}"

- name: "Get service consul"
  ansible.builtin.service_facts:

- name: "Install from repostories"
  throttle: 1
  block:
    - name: "Install consul version: {{ hashi_consul_version }}"
      ansible.builtin.apt:
        update_cache: yes
        name: "consul{{ '='~hashi_consul_version if hashi_consul_version != 'latest' }}"
        state: "{{ 'present' if hashi_consul_version != 'latest' else hashi_consul_version}}"
        allow_downgrade: true
        cache_valid_time: 3600

    - name: "Ensure consul is running"
      ansible.builtin.service:
        name: "{{ hashi_consul_service_name }}"
        state: started
      register: _consul_service_health
      until: _consul_service_health.status.ActiveState == "active"
      retries: 15
      delay: 2
      when:
        ansible_facts.services[hashi_consul_service_name~'.service'] is defined
        and ansible_facts.services[hashi_consul_service_name~'.service']['state'] == 'running'

- name: "Copy systemd service file for consul"
  ansible.builtin.template:
    src: "consul.service.j2"
    dest: "/etc/systemd/system/consul.service"
    owner: root
    group: root
    mode: "0644"
  notify:
    - "systemctl-daemon-reload"
