---
# task/install file for hashicorp_consul
- name: "Get latest release of consul"
  when: hashicorp_consul_version == 'latest'
  block:
    - name: "Get latest consul release from github api"
      ansible.builtin.uri:
        url: "{{ hashicorp_consul_github_api }}/{{ hashicorp_consul_github_project }}/releases/latest"
        return_content: true
      register: _hashicorp_consul_latest_release

    - name: "Set wanted consul version to latest tag"
      ansible.builtin.set_fact:
        _hashicorp_consul_wanted_version: "{{ _hashicorp_consul_latest_release.json['tag_name']|regex_replace('v', '') }}"

- name: "Set wanted consul version to {{ hashicorp_consul_version }}"
  ansible.builtin.set_fact:
    _hashicorp_consul_wanted_version: "{{ hashicorp_consul_version|regex_replace('v', '') }}"
  when: hashicorp_consul_version != 'latest'

- name: "Get current consul version"
  block:
    - name: "Stat consul version file"
      ansible.builtin.stat:
        path: "{{ hashicorp_consul_config_dir }}/.version"
      changed_when: false
      check_mode: false
      register: _hashicorp_consul_version_file

    - name: "Get current consul version"
      ansible.builtin.slurp:
        src: "{{ _hashicorp_consul_version_file.stat.path }}"
      when:
        - _hashicorp_consul_version_file.stat.exists
        - _hashicorp_consul_version_file.stat.isreg
      register: _hashicorp_consul_current_version

- name: "Download and install consul binary"
  when: _hashicorp_consul_current_version is not defined
    or _hashicorp_consul_wanted_version != (_hashicorp_consul_current_version.content|default('')|b64decode)
  block:
    - name: "Set consul package name to download"
      ansible.builtin.set_fact:
        _hashicorp_consul_package_name: >-
          consul_{{ _hashicorp_consul_wanted_version }}_linux_{{ hashicorp_consul_deb_architecture_map[ansible_architecture] }}.zip
        _hashicorp_consul_shasum_file_name: >-
          consul_{{ _hashicorp_consul_wanted_version }}_SHA256SUMS

    - name: "Download checksum file for consul archive"
      ansible.builtin.get_url:
        url: "{{ hashicorp_consul_repository_url }}/{{ _hashicorp_consul_wanted_version }}/{{ _hashicorp_consul_shasum_file_name }}"
        dest: "/tmp/{{ _hashicorp_consul_shasum_file_name }}"
        mode: "0644"
      register: _hashicorp_consul_checksum_file
      until: _hashicorp_consul_checksum_file is succeeded
      retries: 5
      delay: 2
      check_mode: false

    - name: "Extract correct checksum from checksum file"
      ansible.builtin.command:
        cmd: 'grep "{{ _hashicorp_consul_package_name }}" /tmp/{{ _hashicorp_consul_shasum_file_name }}'
      changed_when: false
      register: _hashicorp_consul_expected_checksum_line

    - name: "Parse the expected checksum"
      ansible.builtin.set_fact:
        _hashicorp_consul_expected_checksum: "{{ _hashicorp_consul_expected_checksum_line.stdout.split()[0] }}"

    - name: "Download consul binary archive"
      ansible.builtin.get_url:
        url: "{{ hashicorp_consul_repository_url }}/{{ _hashicorp_consul_wanted_version }}/{{ _hashicorp_consul_package_name }}"
        dest: "/tmp/{{ _hashicorp_consul_package_name }}"
        mode: "0644"
        checksum: "sha256:{{ _hashicorp_consul_expected_checksum }}"
      register: _hashicorp_consul_binary_archive
      until: _hashicorp_consul_binary_archive is succeeded
      retries: 5
      delay: 2
      check_mode: false

    - name: "Create temporary directory for archive decompression"
      ansible.builtin.file:
        path: /tmp/consul
        state: directory
        mode: "0755"

    - name: "Unpack consul archive"
      ansible.builtin.unarchive:
        src: "/tmp/{{ _hashicorp_consul_package_name }}"
        dest: "/tmp/consul"
        owner: "{{ hashicorp_consul_user }}"
        group: "{{ hashicorp_consul_group }}"
        mode: "0755"
        remote_src: true

    - name: "Copy consul binary to {{ hashicorp_consul_binary_path }}"
      ansible.builtin.copy:
        src: /tmp/consul/consul
        dest: "{{ hashicorp_consul_binary_path }}"
        owner: root
        group: root
        mode: "0755"
        remote_src: true
        force: true

    - name: "Update consul version file"
      ansible.builtin.copy:
        content: "{{ _hashicorp_consul_wanted_version }}"
        dest: "{{ hashicorp_consul_config_dir }}/.version"
        owner: "{{ hashicorp_consul_user }}"
        group: "{{ hashicorp_consul_group }}"
        mode: "0600"

    - name: "Set restart-check variable"
      ansible.builtin.set_fact:
        _hashicorp_consul_service_need_restart: true

    - name: "Cleanup temporary directory"
      ansible.builtin.file:
        path: "{{ item }}"
        state: absent
      loop:
        - /tmp/consul
        - /tmp/{{ _hashicorp_consul_package_name }}
        - /tmp/{{ _hashicorp_consul_shasum_file_name }}

- name: "Copy systemd service file for consul"
  ansible.builtin.template:
    src: "consul.service.j2"
    dest: "/etc/systemd/system/consul.service"
    owner: root
    group: root
    mode: "0644"
  register: _hashicorp_consul_unit_file

- name: "Set reload-check & restart-check variable"
  ansible.builtin.set_fact:
    _hashicorp_consul_service_need_reload: true
    _hashicorp_consul_service_need_restart: true
  when: _hashicorp_consul_unit_file.changed # noqa: no-handler
