---
# task/merge_variables file for hashicorp_consul
- name: "Consul | Merge stringified configuration"
  vars:
    _config_to_merge: "{{ hashicorp_consul_configuration_string }}"
  ansible.builtin.set_fact:
    hashicorp_consul_configuration: "{{
      hashicorp_consul_configuration |
      combine(_config_to_merge|from_yaml, recursive=true)
      }}"

- name: "Consul | Merge server specific stringified configuration"
  vars:
    _config_to_merge: "{{ hashicorp_consul_server_configuration_string }}"
  ansible.builtin.set_fact:
    hashicorp_consul_configuration: "{{
      hashicorp_consul_configuration |
      combine(_config_to_merge|from_yaml, recursive=true)
      }}"
  when:
    - hashicorp_consul_enable_server

- name: "Consul | Merge addresses configuration"
  vars:
    _config_to_merge: "{{ hashicorp_consul_address_configuration }}"
  ansible.builtin.set_fact:
    hashicorp_consul_configuration: "{{
      hashicorp_consul_configuration |
      combine(_config_to_merge, recursive=true)
      }}"

- name: "Consul | Merge TLS configuration"
  when: hashicorp_consul_enable_tls
  block:
    - name: "Consul | Merge TLS configuration"
      vars:
        _config_to_merge:
          tls: "{{ hashicorp_consul_tls_configuration }}"
      ansible.builtin.set_fact:
        hashicorp_consul_configuration: "{{
          hashicorp_consul_configuration |
          combine(_config_to_merge, recursive=true)
          }}"

    - name: "Consul | Add certificates directory to extra_files_dir"
      ansible.builtin.set_fact:
        hashicorp_consul_extra_files_list: "{{
          hashicorp_consul_extra_files_list +
          hashicorp_consul_certificates_extra_files_dir
          | unique
          | sort
          }}"

- name: "Consul | Merge extra configuration settings"
  vars:
    _config_to_merge: "{{ hashicorp_consul_extra_configuration }}"
  ansible.builtin.set_fact:
    hashicorp_consul_configuration: "{{
      hashicorp_consul_configuration |
      combine(_config_to_merge, recursive=true)
      }}"

- name: "Consul | Merge log to file configuration"
  vars:
    _config_to_merge: "{{ hashicorp_consul_log_to_file_configuration }}"
  ansible.builtin.set_fact:
    hashicorp_consul_configuration: "{{
      hashicorp_consul_configuration |
      combine(_config_to_merge, recursive=true)
      }}"
  when: hashicorp_consul_enable_log_to_file

- name: "Consul | Merge telemetry configuration"
  block:
    - name: "Consul | Merge prometheus metrics configuration"
      vars:
        _config_to_merge:
          prometheus_retention_time: "{{ hashicorp_consul_prometheus_retention_time }}"
      ansible.builtin.set_fact:
        hashicorp_consul_telemetry_configuration: "{{
          hashicorp_consul_telemetry_configuration |
          combine(_config_to_merge, recursive=true)
          }}"
      when: hashicorp_consul_enable_prometheus_metrics

    - name: "Consul | Merge telemtry configuration"
      vars:
        _config_to_merge:
          telemetry: "{{ hashicorp_consul_telemetry_configuration }}"
      ansible.builtin.set_fact:
        hashicorp_consul_configuration: "{{
          hashicorp_consul_configuration |
          combine(_config_to_merge, recursive=true)
          }}"
