---
# handlers file for hashicorp_consul
- name: "Reload systemd file"
  ansible.builtin.systemd:
    daemon_reload: true
  listen: "systemctl-daemon-reload"

- name: "Enable consul service"
  ansible.builtin.service:
    name: consul
    enabled: true
  listen: "systemctl-enable-consul"

- name: "Start consul service"
  ansible.builtin.service:
    name: consul
    state: restarted
  listen: "systemctl-restart-consul"
  throttle: 1
  when: hashi_consul_start_service
