---
hashi_consul_deploy_method: docker  # deployment method, either host or docker.
hashi_consul_configuration:
  domain: consul
  datacenter: dc1
  primary_datacenter: dc1
  client_addr: "0.0.0.0"
  bind_addr: "{{ ansible_default_ipv4.address }}"
  advertise_addr: "{{ ansible_default_ipv4.address }}"
  data_dir: "/consul/data"
  encrypt: "{{ 'mysupersecretgossipencryptionkey'|b64encode }}"
  server: true
  bootstrap_expect: 1
  retry_join:
    - "{{ ansible_default_ipv4.address }}"
  ui_config:
    enabled: true
  connect:
    enabled: false
  leave_on_terminate: true
  rejoin_after_leave: true
  enable_script_checks: true
  enable_syslog: false
  log_level: INFO
  acl:
    enabled: false
    default_policy: "allow"
    enable_token_persistence: true
    tokens:
      initial_management: ""
      agent: ""
  dns_config:
    allow_stale: true
    enable_truncate: true
    only_passing: true
  ports:
    dns: 8600
    http: 8500
    https: -1
    grpc: 8502
    grpc_tls: 8503
    server: 8300
    serf_lan: 8301
    serf_wan: 8302
    sidecar_min_port: 21000
    sidecar_max_port: 21255
    expose_min_port: 21500
    expose_max_port: 21755
