---
#####################
# ACL configuration #
#####################

hashicorp_consul_acl_configuration:
  enabled: false
  default_policy: "deny"
  enable_token_persistence: true
  tokens:
    initial_management: "1a1f2ce5-3730-47de-9a9c-89e037376bab"
    agent: "1a1f2ce5-3730-47de-9a9c-89e037376bab"
