---
#####################
# ACL configuration #
#####################

hashicorp_consul_acl_configuration:
  enabled: true
  default_policy: "deny"
  enable_token_persistence: true
  tokens:
    initial_management: "1a1f2ce5-3730-47de-9a9c-89e037376bab"
    agent: "1a1f2ce5-3730-47de-9a9c-89e037376bab"

###########
# logging #
###########

hashicorp_consul_log_level: info
hashicorp_consul_enable_log_to_file: true
hashicorp_consul_log_to_file_configuration:
  log_file: "{{ hashicorp_consul_logs_dir }}/consul.log"
  log_rotate_duration: 24h
  log_rotate_max_files: 30
